name: ✅ CI

on: push

jobs:
  Compile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build-type: [Release]
    steps:
      -
        uses: actions/checkout@v3
        with:
          lfs: true
      -
        name: install eigen
        run: |
          git clone https://gitlab.com/libeigen/eigen
          cmake -E make_directory eigen/build
          cmake                                   \
            -DCMAKE_INSTALL_PREFIX=eigen-install  \
            -B eigen/build -S eigen
          cmake --build eigen/build --target install
        shell: bash
      -
        name: 🔧 bezierpp
        run: |
          cmake -E make_directory build
          cmake -DCMAKE_BUILD_TYPE="${{ matrix.build-type }}" \
                -DCMAKE_INSTALL_PREFIX=bezierpp-install       \
                -DCMAKE_PREFIX_PATH=eigen-install             \
                -DBEZIERPP_ENABLE_EXAMPLES=ON                 \
                -DBEZIERPP_ENABLE_INSTALL=ON                  \
                -B build -S .
        shell: bash
      -
        name: 🔨 bezierpp_eigen
        run: cmake --build build --config "${{ matrix.build-type }}" --target "bezierpp_eigen" -j
      -
        name: 🔨 bezierpp install
        run: cmake --build build --config "${{ matrix.build-type }}" --target "install" -j
